
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: 'alpine'
      script: |
        #!/bin/sh
        echo "Cleaning up..."
        rm -rf /workspace/source/*
